### ISSUE TITLE
[Bug] panic: runtime error: integer overflow

### ISSUE THREAD

**Issue by septs** [Dreamacro/clash#1235]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 8080
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: ui

proxy-providers:
  shadowsocks-1:
    type: http
    path: .....
    url: .....
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  shadowsocks-2:
    type: http
    path: .....
    url: .....
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  ssglobal:
    type: http
    path: .....
    url: .....
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: Proxy
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    use:
      - shadowsocks-1
      - shadowsocks-2
      - ssglobal

rules:
  - DOMAIN-KEYWORD,synology,DIRECT
  - DOMAIN-KEYWORD,quickconnect,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
```

</details>

### Clash log

```
-- Logs begin at Tue 2021-02-16 09:06:26 UTC, end at Thu 2021-02-18 02:58:19 UTC. --
Feb 16 09:06:32 dispatch systemd[1]: Started A rule based proxy in Go..
Feb 16 09:06:33 dispatch clash[1246]: time="2021-02-16T09:06:33Z" level=info msg="Start initial provider shadowsocks-1"
Feb 16 09:06:33 dispatch clash[1246]: time="2021-02-16T09:06:33Z" level=info msg="Start initial provider shadowsocks-2"
Feb 16 09:06:33 dispatch clash[1246]: time="2021-02-16T09:06:33Z" level=info msg="Start initial provider ssglobal"
Feb 17 19:41:32 dispatch clash[1246]: panic: runtime error: integer overflow
Feb 17 19:41:32 dispatch clash[1246]: goroutine 500483 [running]:
Feb 17 19:41:32 dispatch clash[1246]: math/bits.Div32(...)
Feb 17 19:41:32 dispatch clash[1246]:         math/bits/bits.go:501
Feb 17 19:41:32 dispatch clash[1246]: math/bits.Div(...)
Feb 17 19:41:32 dispatch clash[1246]:         math/bits/bits.go:488
Feb 17 19:41:32 dispatch clash[1246]: math/big.divWW_g(0xdd45af54, 0xdbcdab7, 0xabda70fa, 0x26d10b4, 0x44)
Feb 17 19:41:32 dispatch clash[1246]:         math/big/arith.go:65 +0xb8
Feb 17 19:41:32 dispatch clash[1246]: math/big.nat.divBasic(0x26d0d80, 0x41, 0x84, 0x26d0fc0, 0x81, 0x84, 0x207f500, 0x40, 0xc4)
Feb 17 19:41:32 dispatch clash[1246]:         math/big/nat.go:763 +0x2ac
Feb 17 19:41:32 dispatch clash[1246]: math/big.nat.divLarge(0x26d0d80, 0x40, 0x84, 0x26d0fc0, 0x80, 0x84, 0x26d06c0, 0x80, 0x85, 0x20aed80, ...)
Feb 17 19:41:32 dispatch clash[1246]:         math/big/nat.go:725 +0x1a8
Feb 17 19:41:32 dispatch clash[1246]: math/big.nat.div(0x26d0d80, 0x40, 0x84, 0x26d0fc0, 0x80, 0x84, 0x26d06c0, 0x80, 0x85, 0x20aed80, ...)
Feb 17 19:41:32 dispatch clash[1246]:         math/big/nat.go:672 +0x298
Feb 17 19:41:32 dispatch clash[1246]: math/big.nat.expNN(0x0, 0x0, 0x0, 0x2367200, 0x40, 0x44, 0x2608b98, 0x1, 0x1, 0x20aed80, ...)
Feb 17 19:41:32 dispatch clash[1246]:         math/big/nat.go:1291 +0x328
Feb 17 19:41:32 dispatch clash[1246]: math/big.(*Int).Exp(0x20e1a98, 0x20e1aa8, 0x20e1a38, 0x20b5f10, 0x2367200)
Feb 17 19:41:32 dispatch clash[1246]:         math/big/int.go:509 +0x138
Feb 17 19:41:32 dispatch clash[1246]: crypto/rsa.encrypt(0x20e1a98, 0x1cf6ce0, 0x20e1aa8, 0x23670e8)
Feb 17 19:41:32 dispatch clash[1246]:         crypto/rsa/rsa.go:389 +0x74
Feb 17 19:41:32 dispatch clash[1246]: crypto/rsa.VerifyPSS(0x1cf6ce0, 0x5, 0x1e4a8a0, 0x20, 0x20, 0x23670e8, 0x100, 0x118, 0x20e1ae8, 0x1e4a8a0, ...)
Feb 17 19:41:32 dispatch clash[1246]:         crypto/rsa/pss.go:295 +0xec
Feb 17 19:41:32 dispatch clash[1246]: crypto/tls.verifyHandshakeSignature(0xe2, 0x41a9c0, 0x1cf6ce0, 0x5, 0x1e4a8a0, 0x20, 0x20, 0x23670e8, 0x100, 0x118, ...)
Feb 17 19:41:32 dispatch clash[1246]:         crypto/tls/auth.go:54 +0x190
Feb 17 19:41:32 dispatch clash[1246]: crypto/tls.(*clientHandshakeStateTLS13).readServerCertificate(0x20e1d0c, 0x0, 0x0)
Feb 17 19:41:32 dispatch clash[1246]:         crypto/tls/handshake_client_tls13.go:484 +0x35c
Feb 17 19:41:32 dispatch clash[1246]: crypto/tls.(*clientHandshakeStateTLS13).handshake(0x20e1d0c, 0x473f25, 0x8)
Feb 17 19:41:32 dispatch clash[1246]:         crypto/tls/handshake_client_tls13.go:85 +0x1bc
Feb 17 19:41:32 dispatch clash[1246]: crypto/tls.(*Conn).clientHandshake(0x21d0000, 0x0, 0x0)
Feb 17 19:41:32 dispatch clash[1246]:         crypto/tls/handshake_client.go:209 +0x498
Feb 17 19:41:32 dispatch clash[1246]: crypto/tls.(*Conn).Handshake(0x21d0000, 0x0, 0x0)
Feb 17 19:41:32 dispatch clash[1246]:         crypto/tls/conn.go:1362 +0xd0
Feb 17 19:41:32 dispatch clash[1246]: github.com/Dreamacro/clash/component/trojan.(*Trojan).StreamConn(0x2169b40, 0x50cf40, 0x1ef8b00, 0x0, 0x50cf40, 0x2e3704, 0x2399860)
Feb 17 19:41:32 dispatch clash[1246]:         github.com/Dreamacro/clash/component/trojan/trojan.go:64 +0x110
Feb 17 19:41:32 dispatch clash[1246]: github.com/Dreamacro/clash/adapters/outbound.(*Trojan).StreamConn(0x21675d0, 0x50cf40, 0x1ef8b00, 0x1c4cf40, 0x2172260, 0x1a, 0x50cf40, 0x1ef8b00)
Feb 17 19:41:32 dispatch clash[1246]:         github.com/Dreamacro/clash/adapters/outbound/trojan.go:32 +0x30
Feb 17 19:41:32 dispatch clash[1246]: github.com/Dreamacro/clash/adapters/outbound.(*Trojan).DialContext(0x21675d0, 0x50a4d8, 0x1c4c340, 0x1c4cf40, 0x9165cd54, 0x713b, 0x756418, 0x1d63e50)
Feb 17 19:41:32 dispatch clash[1246]:         github.com/Dreamacro/clash/adapters/outbound/trojan.go:47 +0x150
Feb 17 19:41:32 dispatch clash[1246]: github.com/Dreamacro/clash/adapters/outbound.(*Proxy).DialContext(0x2169b50, 0x50a4d8, 0x1c4c340, 0x1c4cf40, 0x756418, 0x0, 0x0, 0x0)
Feb 17 19:41:32 dispatch clash[1246]:         github.com/Dreamacro/clash/adapters/outbound/base.go:113 +0x40
Feb 17 19:41:32 dispatch clash[1246]: github.com/Dreamacro/clash/adapters/outbound.(*Proxy).URLTest(0x2169b50, 0x50a4d8, 0x1c4c340, 0x1dbe060, 0x23, 0x0, 0x0, 0x0)
Feb 17 19:41:32 dispatch clash[1246]:         github.com/Dreamacro/clash/adapters/outbound/base.go:180 +0x124
Feb 17 19:41:32 dispatch clash[1246]: github.com/Dreamacro/clash/adapters/provider.(*HealthCheck).check.func1(0x50a4d8, 0x1c4c340, 0x1daa300, 0x2150080, 0x50d938, 0x2169b50)
Feb 17 19:41:32 dispatch clash[1246]:         github.com/Dreamacro/clash/adapters/provider/healthcheck.go:69 +0x48
Feb 17 19:41:32 dispatch clash[1246]: created by github.com/Dreamacro/clash/adapters/provider.(*HealthCheck).check
Feb 17 19:41:32 dispatch clash[1246]:         github.com/Dreamacro/clash/adapters/provider/healthcheck.go:68 +0xec
Feb 17 19:41:32 dispatch systemd[1]: clash.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 17 19:41:32 dispatch systemd[1]: clash.service: Failed with result 'exit-code'.
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Armbian
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. ……

**我预期会发生……？**

**实际上发生了什么？**

**Comment by septs** [comment]
```console
$ ./clash -v
Clash v1.3.5 linux arm Sun Dec 27 11:01:18 UTC 2020
```

**Comment by septs** [comment]
https://github.com/Dreamacro/clash/blob/3600077f3b6997c7b9e7a42a69afde6b17a5e5b1/component/trojan/trojan.go#L49-L69

this issue may be is provider server-side bug.
