### ISSUE TITLE
[Bug] vmess + h2 无法工作并发生 panic

### ISSUE THREAD

**Issue by liberal-boy** [Dreamacro/clash#1338]
### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 7891
# RESTful API for clashr
external-controller: 127.0.0.1:9091
allow-lan: false
mode: rule
log-level: warning

proxies:
  - name: vmessh2
    type: vmess
    server: example.com
    port: "443"
    alterId: 0
    cipher: none
    uuid: uuid
    network: h2
    tls: true
    h2-opts:
      path: /vmess
    udp: false

proxy-groups:
  - name: "PROXY"
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 60
    proxies:
      - vmessh2
rules:
  - DOMAIN-SUFFIX,google.com,PROXY
  - DOMAIN-KEYWORD,google,DIRECT
  - DOMAIN,google.com,DIRECT
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
```

</details>

### Clash log

```
2021/04/09 14:36:16 http: panic serving 127.0.0.1:58118: invalid argument to Intn
goroutine 65 [running]:
net/http.(*conn).serve.func1(0xc0002da000)
	net/http/server.go:1824 +0x153
panic(0x19441a0, 0x1b3ca30)
	runtime/panic.go:971 +0x49a
math/rand.(*Rand).Intn(0xc0001105a0, 0x0, 0xc0002bf5c0)
	math/rand/rand.go:169 +0xa5
math/rand.Intn(...)
	math/rand/rand.go:337
github.com/Dreamacro/clash/component/vmess.(*h2Conn).establishConn(0xc00007b8c0, 0xc0002ff410, 0x10)
	github.com/Dreamacro/clash/component/vmess/h2.go:29 +0x189
github.com/Dreamacro/clash/component/vmess.(*h2Conn).Write(0xc00007b8c0, 0xc0002ff410, 0x10, 0x10, 0xc0002ff410, 0x10, 0x10)
	github.com/Dreamacro/clash/component/vmess/h2.go:80 +0x45
github.com/Dreamacro/clash/component/vmess.(*Conn).sendRequest(0xc0001374a0, 0xc0001374a0, 0xc00007b8c0)
	github.com/Dreamacro/clash/component/vmess/conn.go:62 +0x1e2
github.com/Dreamacro/clash/component/vmess.newConn(0x1b5cba8, 0xc00007b8c0, 0xc000366b40, 0xc00007b8f0, 0x5, 0x0, 0xc0002ff3a0, 0xc0002ff3a0)
	github.com/Dreamacro/clash/component/vmess/conn.go:206 +0x391
github.com/Dreamacro/clash/component/vmess.(*Client).StreamConn(0xc0003bd800, 0x1b5cba8, 0xc00007b8c0, 0xc00007b8f0, 0xc00007b8c0, 0x0, 0x0, 0x0)
	github.com/Dreamacro/clash/component/vmess/vmess.go:78 +0x8f
github.com/Dreamacro/clash/adapters/outbound.(*Vmess).StreamConn(0xc00051a5a0, 0x1b5cba8, 0xc00007b8c0, 0xc0002cc280, 0xc000030228, 0x15, 0x1b5e9e8, 0xc000222180)
	github.com/Dreamacro/clash/adapters/outbound/vmess.go:154 +0x3d6
github.com/Dreamacro/clash/adapters/outbound.(*Vmess).DialContext(0xc00051a5a0, 0x1b56568, 0xc0004465a0, 0xc0002cc280, 0x12e9f0d, 0x606ff5e0, 0xc02c9d83d0, 0x507e57f09724)
	github.com/Dreamacro/clash/adapters/outbound/vmess.go:164 +0xfa
github.com/Dreamacro/clash/adapters/outbound.(*Proxy).DialContext(0xc000366b60, 0x1b56568, 0xc0004465a0, 0xc0002cc280, 0x0, 0x0, 0x0, 0x0)
	github.com/Dreamacro/clash/adapters/outbound/base.go:113 +0x5c
github.com/Dreamacro/clash/adapters/outbound.(*Proxy).URLTest(0xc000366b60, 0x1b56568, 0xc0004465a0, 0xc0000d2720, 0x23, 0xc0000e0000, 0x0, 0x0)
	github.com/Dreamacro/clash/adapters/outbound/base.go:180 +0x23a
github.com/Dreamacro/clash/hub/route.getProxyDelay(0x1b55230, 0xc0000d81c0, 0xc000380d00)
	github.com/Dreamacro/clash/hub/route/proxies.go:114 +0x1fd
net/http.HandlerFunc.ServeHTTP(0x1a8ff98, 0x1b55230, 0xc0000d81c0, 0xc000380d00)
	net/http/server.go:2069 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0000862a0, 0x1b55230, 0xc0000d81c0, 0xc000380d00)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc000092120, 0x1b55230, 0xc0000d81c0, 0xc000380d00)
	net/http/server.go:2069 +0x4b
github.com/Dreamacro/clash/hub/route.findProxyByName.func1(0x1b55230, 0xc0000d81c0, 0xc000380c00)
	github.com/Dreamacro/clash/hub/route/proxies.go:53 +0x2ac
net/http.HandlerFunc.ServeHTTP(0xc000088198, 0x1b55230, 0xc0000d81c0, 0xc000380c00)
	net/http/server.go:2069 +0x4b
github.com/Dreamacro/clash/hub/route.parseProxyName.func1(0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/Dreamacro/clash/hub/route/proxies.go:37 +0x22a
net/http.HandlerFunc.ServeHTTP(0xc0000881b0, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	net/http/server.go:2069 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0000862a0, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x50c
github.com/go-chi/chi.(*Mux).Mount.func1(0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x122
net/http.HandlerFunc.ServeHTTP(0xc0000940c0, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	net/http/server.go:2069 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000086240, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc0000920f0, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	net/http/server.go:2069 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000086240, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x50c
github.com/go-chi/chi.(*Mux).Mount.func1(0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x122
net/http.HandlerFunc.ServeHTTP(0xc000094100, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	net/http/server.go:2069 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/Dreamacro/clash/hub/route/server.go:97 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc0000882a0, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	net/http/server.go:2069 +0x4b
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc000097c00, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/go-chi/chi@v4.1.2+incompatible/chain.go:31 +0x59
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000086120, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc000092040, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	net/http/server.go:2069 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0x1b55230, 0xc0000d81c0, 0xc000380b00)
	github.com/go-chi/cors@v1.1.1/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc000094060, 0x1b55230, 0xc0000d81c0, 0xc000380b00)
	net/http/server.go:2069 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000086120, 0x1b55230, 0xc0000d81c0, 0xc000225000)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2d1
net/http.serverHandler.ServeHTTP(0xc0000d8000, 0x1b55230, 0xc0000d81c0, 0xc000225000)
	net/http/server.go:2887 +0xaa
net/http.(*conn).serve(0xc0002da000, 0x1b565a0, 0xc00029e340)
	net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:3013 +0x3b8
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows 10
* 网路环境或拓扑 (network conditions/topology)
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

根据 v2ray 文档配置的 vmess + h2，本地使用如下 v2ray 配置文件可以正常工作

<details>
  <summary>config.json</summary>

```json
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 8080,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "example.com",
            "port": 443,
            "users": [
              {
                "id": "uuid",
                "alterId": 0
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "h2",
        "httpSettings": { 
          "path": "/vmess"
        },
        "security": "tls"
      }
    }
  ]
}
```

</details>

### 重现问题的具体布骤 Steps to Reproduce

按照 v2ray 文档配置 vmess + h2 后用 clash 连接

**我预期会发生……？**
vmess + h2 正常工作

**实际上发生了什么？**
vmess + h2 无法工作并发生 panic

### 更多信息 More Information

在服务端可以收到来自 clash 的请求，数秒后 clash 报 panic

**Comment by testiknn** [comment]
顺便在这里反馈一个崩溃问题，
clash-core版本：2021.04.08

崩溃的配置方式：
- name: vmess-grpc
  type: vmess
  server: domain.com
  port: 443
  uuid: 9130c770-017a-47b4-899a-7a6db705a7fc
  alterId: 0
  cipher: none
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: 123456gg
  tls: true
  #servername: domain.com
  #skip-cert-verify: true

日志：

time="2021-04-08T16:50:56Z" level=info msg="[TCP] 192.168.1.1:44578 --> 172.217.27.138 match RuleSet(google) using 谷歌[vmess-grpc]"
panic: runtime error: slice bounds out of range [:-13]

goroutine 470 [running]:
github.com/Dreamacro/clash/component/gun.(*Conn).Read(0x173ec60, 0x17ae00d, 0x237, 0x7ff3, 0xd, 0x0, 0x0)
	github.com/Dreamacro/clash/component/gun/gun.go:92 +0x788
io.ReadAtLeast(0x77506008, 0x173ec60, 0x17ae000, 0x244, 0x8000, 0x244, 0x2, 0x0, 0x0)
	io/io.go:328 +0x98
io.ReadFull(...)
	io/io.go:347
github.com/Dreamacro/clash/component/vmess.(*chunkReader).Read(0x173ec90, 0x17ae000, 0x5000, 0x8000, 0x86eaf4, 0x15b9c0, 0x1a16960)
	github.com/Dreamacro/clash/component/vmess/chunk.go:54 +0x234
github.com/Dreamacro/clash/component/vmess.(*Conn).Read(0x1698180, 0x17ae000, 0x5000, 0x8000, 0x0, 0x0, 0xbd2)
	github.com/Dreamacro/clash/component/vmess/conn.go:49 +0x10c
github.com/Dreamacro/clash/tunnel/statistic.(*tcpTracker).Read(0x1798920, 0x17ae000, 0x5000, 0x8000, 0xbd2, 0x0, 0x0)
	github.com/Dreamacro/clash/tunnel/statistic/tracker.go:40 +0x60
io.copyBuffer(0x91d40c, 0x1acc028, 0x91d3f8, 0x1acc030, 0x17ae000, 0x5000, 0x8000, 0x15e9fb0, 0x1acc030, 0x1acc030, ...)
	io/io.go:423 +0x108
io.CopyBuffer(0x91d40c, 0x1acc028, 0x91d3f8, 0x1acc030, 0x17ae000, 0x5000, 0x8000, 0x0, 0x0, 0x2, ...)
	io/io.go:396 +0x7c
github.com/Dreamacro/clash/tunnel.relay.func1(0x927f0c, 0x16ae990, 0x775bf178, 0x1798920, 0x18fdb00)
	github.com/Dreamacro/clash/tunnel/connection.go:154 +0x158
created by github.com/Dreamacro/clash/tunnel.relay
	github.com/Dreamacro/clash/tunnel/connection.go:150 +0x8c

现象描述：
测试使用trojan-grpc一切正常，而切换到vmess-grpc节点就立马崩溃。
trojan-grpc跟vmess-grpc在自动测速时都能正常显示延迟。

**Comment by Dreamacro** [comment]
@liberal-boy 目前有一个 workaround，在 h2-opts 里加上 host 参数，这个 panic 是因为没 host 造成的，后面会在没有 host 的时候默认把 vmess 的 server 放进去

**Comment by Dreamacro** [comment]
在 dev 两个问题应该都修复了

**Comment by liberal-boy** [comment]
@Dreamacro 我把 host 加了上去，panic 不发生了，但依然连不上。log 没有相关提示。修改后的 proxies 部分：

```yaml
proxies:
  - name: vmessh2
    type: vmess
    server: example.com
    port: "443"
    alterId: 0
    cipher: none
    uuid: uuid
    network: h2
    tls: true
    h2-opts:
      host:
        - example.com
      path: /vmess
    udp: false
````

为了排除 vmess-aead 导致故障的可能，我已经把服务端 alterID 设为 1。

**Comment by liberal-boy** [comment]
@Dreamacro v2ray 在不填写 host 时默认行为是使用 `www.example.com` ，但是我在 clash 把 host 设置为 `www.example.com` 故障依然没有解决。
