### ISSUE TITLE
[Bug] SSR Crash

### ISSUE THREAD

**Issue by Kr328** [Dreamacro/clash#1352]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
由于是远程错误报告 没有能力获得配置文件
```

</details>

### Clash log

```
04-14 10:40:11.814 30219 30256 D ClashForAndroid: ClashRuntime: initialize
04-14 10:40:12.047 30219 30279 D ClashForAndroid: Golang runtime keep alive
04-14 10:40:12.071 30219 30258 D ClashForAndroid: CloseModule: initialize
04-14 10:40:12.075 30219 30257 D ClashForAndroid: TunModule: initialize
04-14 10:40:12.076 30219 30282 D ClashForAndroid: ConfigurationModule: initialize
04-14 10:40:12.080 30219 30285 D ClashForAndroid: NetworkObserveModule: initialize
04-14 10:40:12.083 30219 30284 D ClashForAndroid: SideloadDatabaseModule: initialize
04-14 10:40:12.083 30219 30283 D ClashForAndroid: DynamicNotificationModule: initialize
04-14 10:40:12.089 30219 30286 D ClashForAndroid: SuspendModule: initialize
04-14 10:40:12.091 30219 30257 D ClashForAndroid: AppListCacheModule: initialize
04-14 10:40:12.184 30219 30281 I ClashForAndroid: Android tun device created
04-14 10:40:12.202 30219 30257 D ClashForAndroid: Installed 229 packages cached
04-14 10:40:12.209 30219 30271 I ClashForAndroid: Listen TCP redirect 40337
04-14 10:40:12.368 30219 30281 I ClashForAndroid: Start initial compatible provider 🔥 Auto(Best ping)
04-14 10:40:12.368 30219 30281 I ClashForAndroid: Start initial compatible provider 🔰 for iran
04-14 10:40:12.368 30219 30281 I ClashForAndroid: Start initial compatible provider 🔥 Auto2(Best ping)
04-14 10:40:12.368 30219 30281 I ClashForAndroid: Start initial compatible provider ↪️ use (for iran) group
04-14 10:40:12.368 30219 30281 I ClashForAndroid: Start initial compatible provider 🔰 for china
04-14 10:40:12.368 30219 30281 I ClashForAndroid: Start initial compatible provider ↪️ use (for china) group
04-14 10:40:12.389 30219 30271 I ClashForAndroid: HTTP proxy listening at: :7890
04-14 10:40:12.407 30219 30271 I ClashForAndroid: SOCKS proxy listening at: :7891
04-14 10:40:12.412 30219 30256 D ClashForAndroid: Profile AzadNet SubLink loaded
04-14 10:40:14.065 30219     0 E Go      : panic: runtime error: slice bounds out of range [:-352]
04-14 10:40:14.065 30219     0 E Go      : goroutine 1042 [running]:
04-14 10:40:14.067 30219     0 E Go      : github.com/Dreamacro/clash/component/ssr/protocol.(*authChainA).Decode(0x51136a80, 0x50e808d0, 0x50e808e4, 0x0, 0x0)
04-14 10:40:14.067 30219     0 E Go      : 	github.com/Dreamacro/clash@v0.0.0/component/ssr/protocol/auth_chain_a.go:133 +0x6cc
04-14 10:40:14.067 30219     0 E Go      : github.com/Dreamacro/clash/component/ssr/protocol.(*Conn).Read(0x50e808c0, 0x5129c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
04-14 10:40:14.067 30219     0 E Go      : 	github.com/Dreamacro/clash@v0.0.0/component/ssr/protocol/stream.go:30 +0x230
04-14 10:40:14.067 30219     0 E Go      : net/http.(*persistConn).Read(0x5113c5a0, 0x5129c000, 0x1000, 0x1000, 0x38, 0x0, 0x1)
04-14 10:40:14.067 30219     0 E Go      : 	net/http/transport.go:1922 +0x16c
04-14 10:40:14.069 30219     0 E Go      : bufio.(*Reader).fill(0x50c6a8d0)
04-14 10:40:14.069 30219     0 E Go      : 	bufio/bufio.go:101 +0x108
04-14 10:40:14.070 30219     0 E Go      : bufio.(*Reader).Peek(0x50c6a8d0, 0x1, 0x51177840, 0x38, 0x9fe5f948, 0x1, 0x9f7a9dbc)
04-14 10:40:14.070 30219     0 E Go      : 	bufio/bufio.go:139 +0x38
04-14 10:40:14.070 30219     0 E Go      : net/http.(*persistConn).readLoop(0x5113c5a0)
04-14 10:40:14.070 30219     0 E Go      : 	net/http/transport.go:2083 +0x188
04-14 10:40:14.070 30219     0 E Go      : created by net/http.(*Transport).dialConn
04-14 10:40:14.070 30219     0 E Go      : 	net/http/transport.go:1743 +0xa60
04-14 10:40:15.785 30186 30204 E ClashForAndroid: App service crashed
04-14 10:40:15.791 30186 30203 E ClashForAndroid: App service crashed
04-14 10:40:15.998 30186 30186 I ClashForAndroid: App version: versionName = 2.3.14 versionCode = 203014
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Android

* 网路环境或拓扑 (network conditions/topology)
Android VpnService (via tun)

* iptables，如果适用 (if applicable)
无

* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
是

* 其他 (any other information that would be useful)
无

### 说明 Description

SSR 协议 崩溃 (似乎还有 http ?

由于是远程错误报告 只有崩溃日志 不知道如何重现 也不知道具体配置 (

### 使用的版本

Premium 同等于 https://github.com/Dreamacro/clash/commit/7b01e103c256fb929356ab0d14de6b74c55750a7 的 commit

**Comment by Kr328** [comment]
@goomadao 能找个时间稍微检查一下吗

**Comment by goomadao** [comment]
我尽量，不过不能复现可能不太好判断

**Comment by CoelWu** [comment]
我这里也遇到了
