### ISSUE TITLE
[Bug] http: panic serving 127.0.0.1:xxx: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CoelWu** [Dreamacro/clash#1529]
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>

```yaml
mixed-port: 11223
allow-lan: true
external-controller: 127.0.0.1:9090
secret: ''
```

</details>

### Clash log

```
time="2021-08-03T23:11:49+08:00" level=info msg="RESTful API listening at: 127.0.0.1:59547"
time="2021-08-03T23:11:49+08:00" level=error msg="Start Mixed(http and socks) server error: listen tcp :11223: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
2021/08/03 23:11:50 http: panic serving 127.0.0.1:8558: runtime error: invalid memory address or nil pointer dereference
goroutine 50 [running]:
net/http.(*conn).serve.func1(0xc0002a83c0)
	net/http/server.go:1804 +0x153
panic(0x882360, 0xe50270)
	runtime/panic.go:971 +0x49a
github.com/Dreamacro/clash/listener/mixed.(*Listener).Address(0x0, 0xc00002cab0, 0xc000282460)
	github.com/Dreamacro/clash/listener/mixed/mixed.go:30 +0x29
github.com/Dreamacro/clash/listener.GetPorts(0x0)
	github.com/Dreamacro/clash/listener/listener.go:307 +0xc8
github.com/Dreamacro/clash/hub/executor.GetGeneral(0x1)
	github.com/Dreamacro/clash/hub/executor/executor.go:84 +0x2d
github.com/Dreamacro/clash/hub/route.getConfigs(0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	github.com/Dreamacro/clash/hub/route/configs.go:41 +0x29
net/http.HandlerFunc.ServeHTTP(0x991138, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0002800c0, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc0002860a0, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0002800c0, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:71 +0x5aa
github.com/go-chi/chi/v5.(*Mux).Mount.func1(0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:314 +0x176
net/http.HandlerFunc.ServeHTTP(0xc00028a0a0, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	net/http/server.go:2049 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	github.com/Dreamacro/clash/hub/route/server.go:101 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc00029c0d8, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0xc00028c380, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	github.com/go-chi/chi/v5@v5.0.3/chain.go:31 +0x59
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000280000, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc000286040, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	github.com/go-chi/cors@v1.2.0/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc00028a060, 0xa4dc20, 0xc0001de0e0, 0xc0001dc300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000280000, 0xa4dc20, 0xc0001de0e0, 0xc0001dc200)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:88 +0x330
net/http.serverHandler.ServeHTTP(0xc0002d4000, 0xa4dc20, 0xc0001de0e0, 0xc0001dc200)
	net/http/server.go:2867 +0xaa
net/http.(*conn).serve(0xc0002a83c0, 0xa4f5e0, 0xc000081ec0)
	net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:2993 +0x3b8
2021/08/03 23:11:50 http: panic serving 127.0.0.1:8560: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc0001cc140)
	net/http/server.go:1804 +0x153
panic(0x882360, 0xe50270)
	runtime/panic.go:971 +0x49a
github.com/Dreamacro/clash/listener/mixed.(*Listener).Address(0x0, 0xc000152000, 0xc000282460)
	github.com/Dreamacro/clash/listener/mixed/mixed.go:30 +0x29
github.com/Dreamacro/clash/listener.GetPorts(0x0)
	github.com/Dreamacro/clash/listener/listener.go:307 +0xc8
github.com/Dreamacro/clash/hub/executor.GetGeneral(0x1)
	github.com/Dreamacro/clash/hub/executor/executor.go:84 +0x2d
github.com/Dreamacro/clash/hub/route.getConfigs(0xa4dc20, 0xc00014e000, 0xc00011e100)
	github.com/Dreamacro/clash/hub/route/configs.go:41 +0x29
net/http.HandlerFunc.ServeHTTP(0x991138, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0002800c0, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc0002860a0, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0002800c0, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:71 +0x5aa
github.com/go-chi/chi/v5.(*Mux).Mount.func1(0xa4dc20, 0xc00014e000, 0xc00011e100)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:314 +0x176
net/http.HandlerFunc.ServeHTTP(0xc00028a0a0, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	net/http/server.go:2049 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0xa4dc20, 0xc00014e000, 0xc00011e100)
	github.com/Dreamacro/clash/hub/route/server.go:101 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc00029c0d8, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0xc00028c380, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	github.com/go-chi/chi/v5@v5.0.3/chain.go:31 +0x59
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000280000, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc000286040, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	net/http/server.go:2049 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0xa4dc20, 0xc00014e000, 0xc00011e100)
	github.com/go-chi/cors@v1.2.0/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc00028a060, 0xa4dc20, 0xc00014e000, 0xc00011e100)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000280000, 0xa4dc20, 0xc00014e000, 0xc0002c4100)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:88 +0x330
net/http.serverHandler.ServeHTTP(0xc0002d4000, 0xa4dc20, 0xc00014e000, 0xc0002c4100)
	net/http/server.go:2867 +0xaa
net/http.(*conn).serve(0xc0001cc140, 0xa4f5e0, 0xc0002a76c0)
	net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:2993 +0x3b8
2021/08/03 23:11:51 http: panic serving 127.0.0.1:8566: runtime error: invalid memory address or nil pointer dereference
goroutine 36 [running]:
net/http.(*conn).serve.func1(0xc000174000)
	net/http/server.go:1804 +0x153
panic(0x882360, 0xe50270)
	runtime/panic.go:971 +0x49a
github.com/Dreamacro/clash/listener/mixed.(*Listener).Address(0x0, 0xc0002ce330, 0xc000282460)
	github.com/Dreamacro/clash/listener/mixed/mixed.go:30 +0x29
github.com/Dreamacro/clash/listener.GetPorts(0x0)
	github.com/Dreamacro/clash/listener/listener.go:307 +0xc8
github.com/Dreamacro/clash/hub/executor.GetGeneral(0x1)
	github.com/Dreamacro/clash/hub/executor/executor.go:84 +0x2d
github.com/Dreamacro/clash/hub/route.getConfigs(0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	github.com/Dreamacro/clash/hub/route/configs.go:41 +0x29
net/http.HandlerFunc.ServeHTTP(0x991138, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0002800c0, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc0002860a0, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0002800c0, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:71 +0x5aa
github.com/go-chi/chi/v5.(*Mux).Mount.func1(0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:314 +0x176
net/http.HandlerFunc.ServeHTTP(0xc00028a0a0, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	net/http/server.go:2049 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	github.com/Dreamacro/clash/hub/route/server.go:101 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc00029c0d8, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0xc00028c380, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	github.com/go-chi/chi/v5@v5.0.3/chain.go:31 +0x59
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000280000, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc000286040, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	github.com/go-chi/cors@v1.2.0/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc00028a060, 0xa4dc20, 0xc0002d40e0, 0xc0002c4300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000280000, 0xa4dc20, 0xc0002d40e0, 0xc0002c4200)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:88 +0x330
net/http.serverHandler.ServeHTTP(0xc0002d4000, 0xa4dc20, 0xc0002d40e0, 0xc0002c4200)
	net/http/server.go:2867 +0xaa
net/http.(*conn).serve(0xc000174000, 0xa4f5e0, 0xc0002a7780)
	net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:2993 +0x3b8
2021/08/03 23:11:52 http: panic serving 127.0.0.1:8569: runtime error: invalid memory address or nil pointer dereference
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc0001740a0)
	net/http/server.go:1804 +0x153
panic(0x882360, 0xe50270)
	runtime/panic.go:971 +0x49a
github.com/Dreamacro/clash/listener/mixed.(*Listener).Address(0x0, 0xc00002cae0, 0xc000282460)
	github.com/Dreamacro/clash/listener/mixed/mixed.go:30 +0x29
github.com/Dreamacro/clash/listener.GetPorts(0x0)
	github.com/Dreamacro/clash/listener/listener.go:307 +0xc8
github.com/Dreamacro/clash/hub/executor.GetGeneral(0x1)
	github.com/Dreamacro/clash/hub/executor/executor.go:84 +0x2d
github.com/Dreamacro/clash/hub/route.getConfigs(0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	github.com/Dreamacro/clash/hub/route/configs.go:41 +0x29
net/http.HandlerFunc.ServeHTTP(0x991138, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0002800c0, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc0002860a0, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0002800c0, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:71 +0x5aa
github.com/go-chi/chi/v5.(*Mux).Mount.func1(0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:314 +0x176
net/http.HandlerFunc.ServeHTTP(0xc00028a0a0, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	net/http/server.go:2049 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	github.com/Dreamacro/clash/hub/route/server.go:101 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc00029c0d8, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0xc00028c380, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	github.com/go-chi/chi/v5@v5.0.3/chain.go:31 +0x59
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000280000, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc000286040, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	net/http/server.go:2049 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	github.com/go-chi/cors@v1.2.0/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc00028a060, 0xa4dc20, 0xc0001de1c0, 0xc0001dc400)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000280000, 0xa4dc20, 0xc0001de1c0, 0xc0002c4400)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:88 +0x330
net/http.serverHandler.ServeHTTP(0xc0002d4000, 0xa4dc20, 0xc0001de1c0, 0xc0002c4400)
	net/http/server.go:2867 +0xaa
net/http.(*conn).serve(0xc0001740a0, 0xa4f5e0, 0xc0002a78c0)
	net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:2993 +0x3b8
2021/08/03 23:11:53 http: panic serving 127.0.0.1:8570: runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
net/http.(*conn).serve.func1(0xc0001cc1e0)
	net/http/server.go:1804 +0x153
panic(0x882360, 0xe50270)
	runtime/panic.go:971 +0x49a
github.com/Dreamacro/clash/listener/mixed.(*Listener).Address(0x0, 0xc000152030, 0xc000282460)
	github.com/Dreamacro/clash/listener/mixed/mixed.go:30 +0x29
github.com/Dreamacro/clash/listener.GetPorts(0x0)
	github.com/Dreamacro/clash/listener/listener.go:307 +0xc8
github.com/Dreamacro/clash/hub/executor.GetGeneral(0x1)
	github.com/Dreamacro/clash/hub/executor/executor.go:84 +0x2d
github.com/Dreamacro/clash/hub/route.getConfigs(0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	github.com/Dreamacro/clash/hub/route/configs.go:41 +0x29
net/http.HandlerFunc.ServeHTTP(0x991138, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0002800c0, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc0002860a0, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0002800c0, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:71 +0x5aa
github.com/go-chi/chi/v5.(*Mux).Mount.func1(0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:314 +0x176
net/http.HandlerFunc.ServeHTTP(0xc00028a0a0, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	net/http/server.go:2049 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	github.com/Dreamacro/clash/hub/route/server.go:101 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc00029c0d8, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0xc00028c380, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	github.com/go-chi/chi/v5@v5.0.3/chain.go:31 +0x59
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000280000, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc000286040, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	github.com/go-chi/cors@v1.2.0/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc00028a060, 0xa4dc20, 0xc00014e0e0, 0xc00011e300)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000280000, 0xa4dc20, 0xc00014e0e0, 0xc00011e200)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:88 +0x330
net/http.serverHandler.ServeHTTP(0xc0002d4000, 0xa4dc20, 0xc00014e0e0, 0xc00011e200)
	net/http/server.go:2867 +0xaa
net/http.(*conn).serve(0xc0001cc1e0, 0xa4f5e0, 0xc000148080)
	net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:2993 +0x3b8
2021/08/03 23:11:54 http: panic serving 127.0.0.1:8571: runtime error: invalid memory address or nil pointer dereference
goroutine 39 [running]:
net/http.(*conn).serve.func1(0xc000174140)
	net/http/server.go:1804 +0x153
panic(0x882360, 0xe50270)
	runtime/panic.go:971 +0x49a
github.com/Dreamacro/clash/listener/mixed.(*Listener).Address(0x0, 0xc0002ce360, 0xc000282460)
	github.com/Dreamacro/clash/listener/mixed/mixed.go:30 +0x29
github.com/Dreamacro/clash/listener.GetPorts(0x0)
	github.com/Dreamacro/clash/listener/listener.go:307 +0xc8
github.com/Dreamacro/clash/hub/executor.GetGeneral(0x1)
	github.com/Dreamacro/clash/hub/executor/executor.go:84 +0x2d
github.com/Dreamacro/clash/hub/route.getConfigs(0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	github.com/Dreamacro/clash/hub/route/configs.go:41 +0x29
net/http.HandlerFunc.ServeHTTP(0x991138, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0002800c0, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc0002860a0, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0002800c0, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:71 +0x5aa
github.com/go-chi/chi/v5.(*Mux).Mount.func1(0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:314 +0x176
net/http.HandlerFunc.ServeHTTP(0xc00028a0a0, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	net/http/server.go:2049 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	github.com/Dreamacro/clash/hub/route/server.go:101 +0x3fb
net/http.HandlerFunc.ServeHTTP(0xc00029c0d8, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0xc00028c380, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	github.com/go-chi/chi/v5@v5.0.3/chain.go:31 +0x59
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000280000, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:442 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc000286040, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	net/http/server.go:2049 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	github.com/go-chi/cors@v1.2.0/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc00028a060, 0xa4dc20, 0xc0002d41c0, 0xc0002c4500)
	net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000280000, 0xa4dc20, 0xc0002d41c0, 0xc0001dc500)
	github.com/go-chi/chi/v5@v5.0.3/mux.go:88 +0x330
net/http.serverHandler.ServeHTTP(0xc0002d4000, 0xa4dc20, 0xc0002d41c0, 0xc0001dc500)
	net/http/server.go:2867 +0xaa
net/http.(*conn).serve(0xc000174140, 0xa4f5e0, 0xc0001e0100)
	net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:2993 +0x3b8
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
Windows
* 网路环境或拓扑 (network conditions/topology)
WIFI
* iptables，如果适用 (if applicable)
不适用
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
不适用
* 其他 (any other information that would be useful)
……

### 重现问题的具体布骤 Steps to Reproduce

1.启动Clash
2.客户端调用Restful API
3.发生panic

**我预期会发生……？**
没有panic发生

**实际上发生了什么？**
发生panic

### 更多信息 More Information
最新版commit修复listener问题后发生

**Comment by Dreamacro** [comment]
犯了个基础错误，修了

```
var a *int = nil
var b interface{} = a

a != nil // false
b != nil // true
a == b // true
```

**Comment by CoelWu** [comment]
感谢D大
