### ISSUE TITLE
[Bug] Wintun 0.14 兼容性问题，更换0.13的DLL无异常

### ISSUE THREAD

**Issue by daiyeqi** [Dreamacro/clash#1671]
### Verify steps

- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [ ]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [ ]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2021.09.15

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
  enable: true
  stack: system # or gvisor
  # dns-hijack:
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53
  auto-route: true # auto set global route
  auto-detect-interface: true # conflict with interface-name
```

### Clash log

```shell
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x7760dd]

goroutine 1 [running, locked to thread]:
runtime.throw({0xc28be6, 0x269f84affff})
        runtime/panic.go:1198 +0x76 fp=0xc00014b100 sp=0xc00014b0d0 pc=0x4d6d36
runtime.sigpanic()
        runtime/signal_windows.go:260 +0x10c fp=0xc00014b148 sp=0xc00014b100 pc=0x4e9c6c
golang.org/x/sys/windows.UTF16PtrToString(0x4e0fd1)
        golang.org/x/sys@v0.0.0-20210906170528-6f6e22806c34/windows/syscall_windows.go:132 +0x1d fp=0xc00014b190 sp=0xc00014b148 pc=0x7760dd
github.com/Dreamacro/clash/listener/device/wintun.loadDLL.func1.1(0x269f85e2428, 0x0)
        github.com/Dreamacro/clash/listener/device/wintun/wintun.go:59 +0x1c fp=0xc00014b1d8 sp=0xc00014b190 pc=0x97d9fc
runtime.call16(0x0, 0xc6a048, 0xc00014b260, 0x0, 0x0, 0x10, 0xc00014b4b8)
        runtime/asm_amd64.s:625 +0x50 fp=0xc00014b1f8 sp=0xc00014b1d8 pc=0x502950
runtime.callbackWrap(0xdde51ff030)
        runtime/syscall_windows.go:378 +0x134 fp=0xc00014b5d8 sp=0xc00014b1f8 pc=0x4f1f34
runtime.cgocallbackg1(0x4f1e00, 0x100000000000012, 0x0)
        runtime/cgocall.go:306 +0x29a fp=0xc00014b6a8 sp=0xc00014b5d8 pc=0x4a457a
runtime.cgocallbackg(0xc00007e000, 0x300000002, 0xc00007e000)
        runtime/cgocall.go:232 +0x106 fp=0xc00014b740 sp=0xc00014b6a8 pc=0x4a4206
runtime.cgocallbackg(0x4f1e00, 0xdde51ff030, 0x0)
        <autogenerated>:1 +0x36 fp=0xc00014b768 sp=0xc00014b740 pc=0x506736
runtime.cgocallback(0x4a408c, 0x506040, 0x1206a40)
        runtime/asm_amd64.s:915 +0xd7 fp=0xc00014b790 sp=0xc00014b768 pc=0x504557
runtime.systemstack_switch()
        runtime/asm_amd64.s:350 fp=0xc00014b798 sp=0xc00014b790 pc=0x502400
runtime.cgocall(0x506040, 0x1206a40)
        runtime/cgocall.go:166 +0xac fp=0xc00014b7d0 sp=0xc00014b798 pc=0x4a408c
syscall.Syscall(0x7ffdc34d3a90, 0x2, 0xc0001f8200, 0xc000390210, 0x0)
        runtime/syscall_windows.go:479 +0xf4 fp=0xc00014b808 sp=0xc00014b7d0 pc=0x500e54
syscall.Syscall(0xc0001b8330, 0x0, 0x51cac0, 0xc00012b0a4, 0x51ca80)
        <autogenerated>:1 +0x2b fp=0xc00014b858 sp=0xc00014b808 pc=0x506f2b
github.com/Dreamacro/clash/listener/device/wintun.(*Pool).OpenAdapter(0xc0001f8200, {0xc28948, 0x85dabd})
        github.com/Dreamacro/clash/listener/device/wintun/wintun.go:98 +0xc5 fp=0xc00014b8d0 sp=0xc00014b858 pc=0x97d265
github.com/Dreamacro/clash/listener/device.CreateTUNWithRequestedGUID({0xc28948, 0x5}, 0xc00014b980, 0x2328)
        github.com/Dreamacro/clash/listener/device/tun_windows.go:117 +0x49 fp=0xc00014b948 sp=0xc00014b8d0 pc=0x97e9c9
github.com/Dreamacro/clash/listener/device.CreateTUN({0xc28948, 0x5}, 0xc00014ba18)
        github.com/Dreamacro/clash/listener/device/tun_windows.go:106 +0xcc fp=0xc00014b9a0 sp=0xc00014b948 pc=0x97e94c
github.com/Dreamacro/clash/listener/tun.New(0xc0001545a0, 0xc000154600, 0xc0001b9c20, {0xc0001e7330, 0x2, 0x4ad4e7})
        github.com/Dreamacro/clash/listener/tun/adapter.go:272 +0x67 fp=0xc00014ba28 sp=0xc00014b9a0 pc=0xaa0ca7
github.com/Dreamacro/clash/listener.ReCreateTun(0xe, 0xc000390190, {0x1, 0xc0001b9c20, {0xc00012b5aa, 0x6}, 0x1, 0x1, {0x0, 0x0, ...}, ...})
        github.com/Dreamacro/clash/listener/listener.go:238 +0x8e5 fp=0xc00014bbb0 sp=0xc00014ba28 pc=0xaa29e5
github.com/Dreamacro/clash/hub/executor.updateTun(0xc0001d35f0)
        github.com/Dreamacro/clash/hub/executor/executor.go:139 +0x138 fp=0xc00014bce8 sp=0xc00014bbb0 pc=0xaa4118
github.com/Dreamacro/clash/hub/executor.ApplyConfig(0xc0001a8400, 0xd0)
        github.com/Dreamacro/clash/hub/executor/executor.go:81 +0x135 fp=0xc00014bd38 sp=0xc00014bce8 pc=0xaa3db5
github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0xc29541})
        github.com/Dreamacro/clash/hub/hub.go:48 +0x18d fp=0xc00014bd88 sp=0xc00014bd38 pc=0xacb58d
main.main()
        github.com/Dreamacro/clash/main.go:96 +0x757 fp=0xc00014bf80 sp=0xc00014bd88 pc=0xacc0d7
runtime.main()
        runtime/proc.go:255 +0x217 fp=0xc00014bfe0 sp=0xc00014bf80 pc=0x4d92f7
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc00014bfe8 sp=0xc00014bfe0 pc=0x504781

goroutine 19 [chan receive]:
github.com/Dreamacro/clash/common/observable.(*Observable).process(0xc000124580)
        github.com/Dreamacro/clash/common/observable/observable.go:16 +0x50
created by github.com/Dreamacro/clash/common/observable.NewObservable
        github.com/Dreamacro/clash/common/observable/observable.go:63 +0xbb

goroutine 20 [chan receive]:
github.com/Dreamacro/clash/tunnel/statistic.(*Manager).handle(0xc000154540)
        github.com/Dreamacro/clash/tunnel/statistic/manager.go:83 +0x93
created by github.com/Dreamacro/clash/tunnel/statistic.init.0
        github.com/Dreamacro/clash/tunnel/statistic/manager.go:22 +0x185

goroutine 21 [chan receive]:
github.com/Dreamacro/clash/tunnel.process()
        github.com/Dreamacro/clash/tunnel/tunnel.go:134 +0x88
created by github.com/Dreamacro/clash/tunnel.init.0
        github.com/Dreamacro/clash/tunnel/tunnel.go:45 +0x25

goroutine 5 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 6 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 7 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 8 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 9 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 10 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 11 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 12 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 13 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 14 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 15 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 16 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 34 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 35 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 36 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 37 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 38 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 39 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 40 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 41 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 42 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 43 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 44 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 45 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
        github.com/Dreamacro/clash/tunnel/tunnel.go:119 +0x4d
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:130 +0x48

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x269f8602b98, 0x72)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc0001a5198, 0x400, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc0001a5198, 0xc6a918)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).ReadFrom(0xc0001a5180, {0xc00029a000, 0x40, 0x2030000})
        internal/poll/fd_windows.go:581 +0x155
net.(*netFD).readFrom(0xc0001a5180, {0xc00029a000, 0x0, 0xc0001dbca0})
        net/fd_posix.go:62 +0x29
net.(*UDPConn).readFrom(0xc000088800, {0xc00029a000, 0x0, 0x18}, 0xc00028e030)
        net/udpsock_posix.go:47 +0x3e
net.(*UDPConn).readFromUDP(0xc00014e640, {0xc00029a000, 0xb3b6c0, 0xc0001dbd01}, 0xc0001dbd78)
        net/udpsock.go:116 +0x31
net.(*UDPConn).ReadFrom(0x200, {0xc00029a000, 0x200, 0x200})
        net/udpsock.go:125 +0x50
github.com/miekg/dns.ReadFromSessionUDP(0xc0001dee60, {0xc00029a000, 0x1205d20, 0x1205d20})
        github.com/miekg/dns@v1.1.43/udp_windows.go:19 +0x25
github.com/miekg/dns.(*Server).readUDP(0xc0001ded80, 0xc00014e640, 0xc0001ded01)
        github.com/miekg/dns@v1.1.43/server.go:687 +0x110
github.com/miekg/dns.defaultReader.ReadUDP({0xd1fcd6}, 0xd358e0, 0xc0001ded80)
        github.com/miekg/dns@v1.1.43/server.go:174 +0x19
github.com/miekg/dns.(*Server).serveUDP(0xc0001ded80, {0xd45580, 0xc00014e640})
        github.com/miekg/dns@v1.1.43/server.go:501 +0x2a9
github.com/miekg/dns.(*Server).ActivateAndServe(0xc0001ded80)
        github.com/miekg/dns@v1.1.43/server.go:358 +0x27d
github.com/Dreamacro/clash/dns.ReCreateServer.func1()
        github.com/Dreamacro/clash/dns/server.go:123 +0x25
created by github.com/Dreamacro/clash/dns.ReCreateServer
        github.com/Dreamacro/clash/dns/server.go:122 +0x2e6

goroutine 23 [select]:
github.com/Dreamacro/clash/common/cache.(*janitor).process(0xc0001e7200, 0x0)
        github.com/Dreamacro/clash/common/cache/cache.go:81 +0x89
created by github.com/Dreamacro/clash/common/cache.New
        github.com/Dreamacro/clash/common/cache/cache.go:102 +0xf7

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x269f8602ab0, 0x72)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc0000cbd38, 0x4ad194, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc0001a5418, 0xc0000cbd40)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).acceptOne(0xc0001a5400, 0x184, {0xc0000d2000, 0x0, 0x0}, 0x0)
        internal/poll/fd_windows.go:810 +0x6d
internal/poll.(*FD).Accept(0xc0001a5400, 0xc0000cbf18)
        internal/poll/fd_windows.go:844 +0x1d6
net.(*netFD).accept(0xc0001a5400)
        net/fd_windows.go:139 +0x65
net.(*TCPListener).accept(0xc000116d98)
        net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc000116d98)
        net/tcpsock.go:262 +0x3d
github.com/Dreamacro/clash/listener/http.NewWithAuthenticate.func1()
        github.com/Dreamacro/clash/listener/http/server.go:54 +0x45
created by github.com/Dreamacro/clash/listener/http.NewWithAuthenticate
        github.com/Dreamacro/clash/listener/http/server.go:52 +0x156

goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0x269f86029c8, 0x72)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc000399d30, 0x4ad194, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc0001a5698, 0xc000399d38)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).acceptOne(0xc0001a5680, 0x1a8, {0xc000208000, 0x0, 0x0}, 0x0)
        internal/poll/fd_windows.go:810 +0x6d
internal/poll.(*FD).Accept(0xc0001a5680, 0xc000399f10)
        internal/poll/fd_windows.go:844 +0x1d6
net.(*netFD).accept(0xc0001a5680)
        net/fd_windows.go:139 +0x65
net.(*TCPListener).accept(0xc000116df8)
        net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc000116df8)
        net/tcpsock.go:262 +0x3d
github.com/Dreamacro/clash/listener/socks.New.func1()
        github.com/Dreamacro/clash/listener/socks/tcp.go:50 +0x4e
created by github.com/Dreamacro/clash/listener/socks.New
        github.com/Dreamacro/clash/listener/socks/tcp.go:48 +0x13e

goroutine 26 [IO wait]:
internal/poll.runtime_pollWait(0x269f86028e0, 0x72)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc0001a5918, 0x4b7a85, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc0001a5918, 0xc6a918)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).ReadFrom(0xc0001a5900, {0xc000210000, 0xc00, 0x2030000})
        internal/poll/fd_windows.go:581 +0x155
net.(*netFD).readFrom(0xc0001a5900, {0xc000210000, 0x0, 0x0})
        net/fd_posix.go:62 +0x29
net.(*UDPConn).readFrom(0xc000302000, {0xc000210000, 0x0, 0x8000}, 0xc000218000)
        net/udpsock_posix.go:47 +0x3e
net.(*UDPConn).readFromUDP(0xc00014e658, {0xc000210000, 0x7eb278, 0xc000168a98}, 0x0)
        net/udpsock.go:116 +0x31
net.(*UDPConn).ReadFrom(0x0, {0xc000210000, 0x5000, 0x8000})
        net/udpsock.go:125 +0x50
github.com/Dreamacro/clash/listener/socks.NewUDP.func1()
        github.com/Dreamacro/clash/listener/socks/udp.go:53 +0x76
created by github.com/Dreamacro/clash/listener/socks.NewUDP
        github.com/Dreamacro/clash/listener/socks/udp.go:50 +0x14f
```

### Description

更新了wintun0.14的dll，发现程序启动报错，换回0.13版本的dll后就不报错了。

--
Wintun 0.14 AMD64 SHA1：42913F572D1F309FBEC841AF19668C2DB8E094C1

**Comment by Dreamacro** [comment]
wintun 0.14 换了实现方式，是一个 breakchange。已经适配好了，新版本会最低支持 0.14

**Comment by Dreamacro** [comment]
[clash-windows-amd64.exe.zip](https://github.com/Dreamacro/clash/files/7344955/clash-windows-amd64.exe.zip) 你可以先试试 （这个版本还包含 cache 换格式的 change）

**Comment by kingforme** [comment]
> [clash-windows-amd64.exe.zip](https://github.com/Dreamacro/clash/files/7344955/clash-windows-amd64.exe.zip) 你可以先试试 （这个版本还包含 cache 换格式的 change）

请问,这个程序如何替换旧的？
