### ISSUE TITLE
[Bug] Premium 2022.04.17 mips64 crashes, script 相关

### ISSUE THREAD

**Issue by sskaje** [Dreamacro/clash#2139]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Premium 2022.04.17

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
root@ER3:/home/ubnt# cat /config/clash/utun/rulesets/no-quic.yaml 
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443

rules:
  - SCRIPT,quic,REJECT
```

### Clash log

```shell
2022/05/18 05:02:10 script:1:22: compiler.lookup(dst_port): scope = 5
panic: script:1:22: compiler.lookup(dst_port): scope = 5
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x79f2ec]

goroutine 28520 [running]:
github.com/Dreamacro/clash/tunnel.resolveMetadata.func1()
	github.com/Dreamacro/clash/tunnel/tunnel.go:196 +0x30c
panic({0x8ef260, 0xc00030d450})
	runtime/panic.go:838 +0x29c
log.Panicf({0xa4be6a, 0x23}, {0xc00014d128, 0x3, 0x3})
	log/log.go:392 +0xcc
go.starlark.net/internal/compile.(*fcomp).lookup(0xc00014d878, 0xc000388180)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1034 +0x268
go.starlark.net/internal/compile.(*fcomp).expr(0xc00014d878, {0xb67d00, 0xc000388180})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1289 +0x13f8
go.starlark.net/internal/compile.(*fcomp).expr(0xc00014d878, {0xb67a98, 0xc000388200})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1428 +0x20c
go.starlark.net/internal/compile.(*fcomp).expr(0xc00014d878, {0xb67a98, 0xc000388240})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1418 +0x55c
go.starlark.net/internal/compile.(*fcomp).stmt(0xc00014d878, {0xb67ec0, 0xc0010fe0f0})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1205 +0x308
go.starlark.net/internal/compile.(*fcomp).stmts(0xc00014d878, {0xc00014da30, 0x1, 0x1})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1040 +0x90
go.starlark.net/internal/compile.(*pcomp).function(0xc00108ecc0, {0xa314a8, 0x6}, {0xc00003cb50, 0x1, 0x1}, {0xc0004c5a30, 0x1, 0x1}, {0x0, ...}, ...)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:535 +0x41c
go.starlark.net/internal/compile.File({0xc0004c5a30, 0x1, 0x1}, {0xc00003cb50, 0x1, 0x1}, {0xa314a8, 0x6}, {0x0, 0x0, ...}, ...)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:502 +0x1fc
go.starlark.net/internal/compile.Expr({0xb67a98, 0xc000388240}, {0xa314a8, 0x6}, {0x0, 0x0, 0x0})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:489 +0x15c
go.starlark.net/starlark.makeExprFunc({0xb67a98, 0xc000388240}, 0xc0010fe060)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/eval.go:561 +0x190
go.starlark.net/starlark.EvalExpr(0xc0006afce0, {0xb67a98, 0xc000388240}, 0xc0010fe060)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/eval.go:537 +0x4c
github.com/Dreamacro/clash/rule.(*Script).Match(0xc000388280, 0xc000533680)
	github.com/Dreamacro/clash/rule/script.go:25 +0x94
github.com/Dreamacro/clash/tunnel.match(0xc000533680)
	github.com/Dreamacro/clash/tunnel/tunnel.go:461 +0x844
github.com/Dreamacro/clash/tunnel.resolveMetadata({0xffcbec2098, 0xc000ff7fb0}, 0xc000533680)
	github.com/Dreamacro/clash/tunnel/tunnel.go:213 +0x1cc
github.com/Dreamacro/clash/tunnel.handleTCPConn({0xb67868, 0xc000ff7fb0})
	github.com/Dreamacro/clash/tunnel/tunnel.go:367 +0x1b8
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:139 +0xc0
```

### Description

EdgeRouter Lite (mips64) + Premium 2022.04.17

非必现，大多数情况可能都正常，偶尔突然就发现crash 崩了。大概最近一个月崩了3-4次。

Clash 每4 个小时重启一次。这一次 crash 是距离成功重启 40分钟。更早的日志没有留。

Clash stack trace 里看到的是脚本相关的，所以配置里只提供了脚本的部分，相关配置是原样从 wiki 抄的。

已升级到了2022.05.17，观察几天看看。

**Comment by Dreamacro** [comment]
没找到 root case，从 starlack 的源码来看那个地方不应该会走到 panic。如果最新的还有问题的话麻烦更新一下进展，怀疑是 go 在 mips 架构上的问题。

**Comment by OUZYcn** [comment]
@sskaje 可否请教如何在edgerouter上部署clash？

**Comment by sskaje** [comment]
> @sskaje 可否请教如何在edgerouter上部署clash？

https://github.com/sskaje/ubnt-clash

**Comment by sskaje** [comment]
@Dreamacro  新版也有


```
2022/05/23 13:28:00 script:1:22: compiler.lookup(dst_port): scope = 5
panic: script:1:22: compiler.lookup(dst_port): scope = 5
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x7899c4]

goroutine 350106 [running]:
github.com/Dreamacro/clash/tunnel.resolveMetadata.func1()
	github.com/Dreamacro/clash/tunnel/tunnel.go:196 +0x30c
panic({0x8cd2c0, 0xc0016c1180})
	runtime/panic.go:838 +0x29c
log.Panicf({0xa22d24, 0x23}, {0xc0004a5128, 0x3, 0x3})
	log/log.go:392 +0xcc
go.starlark.net/internal/compile.(*fcomp).lookup(0xc0004a5878, 0xc000370440)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1034 +0x268
go.starlark.net/internal/compile.(*fcomp).expr(0xc0004a5878, {0xb3e6c0, 0xc000370440})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1289 +0x13f8
go.starlark.net/internal/compile.(*fcomp).expr(0xc0004a5878, {0xb3e458, 0xc0003704c0})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1428 +0x20c
go.starlark.net/internal/compile.(*fcomp).expr(0xc0004a5878, {0xb3e458, 0xc000370500})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1418 +0x55c
go.starlark.net/internal/compile.(*fcomp).stmt(0xc0004a5878, {0xb3e880, 0xc0011c1200})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1205 +0x308
go.starlark.net/internal/compile.(*fcomp).stmts(0xc0004a5878, {0xc0004a5a30, 0x1, 0x1})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:1040 +0x90
go.starlark.net/internal/compile.(*pcomp).function(0xc0016aee00, {0xa0884b, 0x6}, {0xc000386100, 0x1, 0x1}, {0xc00073ea30, 0x1, 0x1}, {0x0, ...}, ...)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:535 +0x41c
go.starlark.net/internal/compile.File({0xc00073ea30, 0x1, 0x1}, {0xc000386100, 0x1, 0x1}, {0xa0884b, 0x6}, {0x0, 0x0, ...}, ...)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:502 +0x1fc
go.starlark.net/internal/compile.Expr({0xb3e458, 0xc000370500}, {0xa0884b, 0x6}, {0x0, 0x0, 0x0})
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/internal/compile/compile.go:489 +0x15c
go.starlark.net/starlark.makeExprFunc({0xb3e458, 0xc000370500}, 0xc0011c0f00)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/eval.go:561 +0x190
go.starlark.net/starlark.EvalExpr(0xc000833da0, {0xb3e458, 0xc000370500}, 0xc0011c0f00)
	go.starlark.net@v0.0.0-20220328144851-d1966c6b9fcd/starlark/eval.go:537 +0x4c
github.com/Dreamacro/clash/rule.(*Script).Match(0xc00035d6d0, 0xc000f63b90)
	github.com/Dreamacro/clash/rule/script.go:28 +0xa0
github.com/Dreamacro/clash/tunnel.match(0xc000f63b90)
	github.com/Dreamacro/clash/tunnel/tunnel.go:461 +0x844
github.com/Dreamacro/clash/tunnel.resolveMetadata({0xffce172dd8, 0xc00093b380}, 0xc000f63b90)
	github.com/Dreamacro/clash/tunnel/tunnel.go:213 +0x1cc
github.com/Dreamacro/clash/tunnel.handleTCPConn({0xb3e228, 0xc00093b380})
	github.com/Dreamacro/clash/tunnel/tunnel.go:367 +0x1b8
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:139 +0xc0
```


3.7k+ 的都是带crash的。
```
root@ER3:/tmp# ls -al clash_*
-rw-r--r--    1 root     root           524 May 22 15:17 clash_1653233822.log
-rw-r--r--    1 root     root           524 May 22 15:42 clash_1653236041.log
-rw-r--r--    1 root     root          3744 May 23 13:28 clash_1653312482.log
-rw-r--r--    1 root     root          3744 May 24 01:35 clash_1653356161.log
-rw-r--r--    1 root     root          3824 May 25 05:20 clash_1653456061.log
-rw-r--r--    1 root     root          3825 May 25 14:49 clash_1653490201.log
-rw-r--r--    1 root     root          3824 May 25 16:54 clash_1653497701.log
-rw-r--r--    1 root     root           605 May 25 18:00 clash_utun.log
```

**Comment by sskaje** [comment]
上一条评论是 2022.05.17 的。
05.31 换用 2022.05.18，用了11天了，没遇到问题。
