### ISSUE TITLE
Mac 电脑端 clash for mac通过 clash api使用 http://127.0.0.1:9090/proxies/Proxy 切换代理正常，但同样的代码 在clash for windows 切换错误[Bug] 

### ISSUE THREAD

**Issue by jackwan990** [Dreamacro/clash#2239]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [ ]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash for windows v0.19.10

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090
secret: ""



### Clash log

```shell
无
```

### Description

Mac 电脑端 通过 clash api使用 http://127.0.0.1:9090/proxies/Proxy 切换代理正常，但同样的代码 在clash for windows 下进行
clash api使用 http://127.0.0.1:9090/proxies/Proxy 切换代理错误[Bug] 

`Traceback (most recent call last):
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001557C7E0520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9090): Max retries exceeded with url: /proxies/Proxy/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001557C7E0520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\macbookpro\Desktop\Twiiter\Twiiterv3 带切换代理\Twiiter\proxy.py", line 103, in <module>
    print(pr.get_all_proxy())
  File "C:\Users\macbookpro\Desktop\Twiiter\Twiiterv3 带切换代理\Twiiter\proxy.py", line 76, in get_all_proxy
    response = requests.get('http://127.0.0.1:9090/proxies/Proxy/',headers=Proxy.headers)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9090): Max retries exceeded with url: /proxies/Proxy/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001557C7E0520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[Finished in 2.9s]`

**Comment by archzi** [comment]
你的服务器节点暴露了。请赶紧删掉

**Comment by jackwan990** [comment]
您好！谢谢提醒，这边已经删除了服务器节点信息。

**Comment by Dreamacro** [comment]
把 log level 改成 info 再看日志

**Comment by jackwan990** [comment]
> 把 log level 改成 info 再看日志

<img width="682" alt="图片" src="https://user-images.githubusercontent.com/109976887/181144829-4355104e-c72d-441e-af36-8dc7780240e5.png">

**Comment by Dreamacro** [comment]
刚启动一定有个 listen，我觉得就是没 listen 上

**Comment by Dreamacro** [comment]
而且 clash for windows 能够使用，说明都是正常的

**Comment by jackwan990** [comment]
> 而且 clash for windows 能够使用，说明都是正常的

是的，clash for windows是正常使用的，可以进行代理。
通过clash api使用 http://127.0.0.1:9090/proxies/Proxy 切换代理 
 python 代码切换
response = requests.get('http://127.0.0.1:9090/proxies/Proxy/') 反馈回来的信息就是

`Traceback (most recent call last):
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
conn = connection.create_connection(
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
raise err
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by Dreamacro** [comment]
@jackwan990 启动时日志会有的，看最开始的日志

**Comment by fanvinga** [comment]
Clash for Windows会忽略掉profiles里面定义的controller地址,然后随机化成一个在Clash for Windows首页可以查看的端口,建议查看Clash for Windows的设置中的端口值进行切换
