### ISSUE TITLE
[Bug] gvisor 报错

### ISSUE THREAD

**Issue by Victor2333** [Dreamacro/clash#2309]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.08.26 priume

### Clash config

```yaml
tun:
  enable: true
  stack: gvisor# or gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
```

### Clash log

```shell
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: 02:54:42 WRN [Gvisor] can't create TCP Endpoint in ipstack error=connection was refused
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: 02:54:42 WRN [Gvisor] can't create TCP Endpoint in ipstack error=connection was refused
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa43846]
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: goroutine 1207684 [running]:
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*timer).enable(0xc0005ae8e0, 0xa2f8c6?)
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: #011gvisor.dev/gvisor@v0.0.0-20220428010907-8082b77961ba/pkg/tcpip/transport/tcp/timer.go:141 +0x26
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).resetKeepaliveTimer(0xc0005ae600, 0x1)
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: #011gvisor.dev/gvisor@v0.0.0-20220428010907-8082b77961ba/pkg/tcpip/transport/tcp/connect.go:1344 +0xb1
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).OnKeepAliveSet(0xc000714140?, 0xf0?)
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: #011gvisor.dev/gvisor@v0.0.0-20220428010907-8082b77961ba/pkg/tcpip/transport/tcp/endpoint.go:1739 +0x2d
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: gvisor.dev/gvisor/pkg/tcpip.(*SocketOptions).SetKeepAlive(0xc000714140?, 0x0?)
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: #011gvisor.dev/gvisor@v0.0.0-20220428010907-8082b77961ba/pkg/tcpip/socketops.go:336 +0x27
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: github.com/Dreamacro/clash/listener/stack/gvisor.(*Gvisor).Start.func1(0x4?)
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: #011github.com/Dreamacro/clash/listener/stack/gvisor/gvisor.go:182 +0xa5
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
Sep 17 02:54:42 victor-ubuntu-server clash[22563]: #011gvisor.dev/gvisor@v0.0.0-20220428010907-8082b77961ba/pkg/tcpip/transport/tcp/forwarder.go:97 +0x390
```

### Description

stack使用gvisor报错

**Comment by Dreamacro** [comment]
是在什么设备什么系统发生的

**Comment by Victor2333** [comment]
ubuntu 22.04

**Comment by Victor2333** [comment]
x86 64 ubuntu 22.04

**Comment by Dreamacro** [comment]
是启动就立马有的还是运行了一段时间才发生的？

**Comment by Victor2333** [comment]
运行了一段时间后发生的

**Comment by Dreamacro** [comment]
试一下最新的 latest 版本，看看还会不会出现 panic

**Comment by Victor2333** [comment]
重启service后 panic 问题复现不了。之前是使用 iphone 14 pro 投屏youtube内容到小米电视上的时候 突然就挂了 但是现在同样的操作 在 2022.08.26 premium上 复现不了这个问题 先closed了 以后碰到了 能复现了 再reopen。

**Comment by Jingyu-Yan** [comment]
我在win10上使用tun时也遇见了这个错误，重启clash就正常，而且我最近clash挂在那久了就会这样
