### ISSUE TITLE
[Bug] proxy-providers无法使用

### ISSUE THREAD

**Issue by Kry5ta1** [Dreamacro/clash#2522]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.13.0-1-g81b1e9f

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
proxy-providers:
  Amy:
    type: http
    path: "./proxy_provider/Amy.yaml"
    url: *********
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
```

### Clash log

```shell
2023-02-03 17:13:10 第六步：删除 OpenClash 残留文件...
2023-02-03 17:13:09 第五步: 重启 Dnsmasq 程序...
2023-02-03 17:13:09 第四步: 关闭 Clash 主程序...
2023-02-03 17:13:09 第三步: 关闭 OpenClash 守护程序...
2023-02-03 17:13:08 第二步: 删除 OpenClash 防火墙规则...
2023-02-03 17:13:08 第一步: 备份当前策略组状态...
2023-02-03 17:13:08 OpenClash 开始关闭...
2023-02-03 17:13:05 错误：无法获取 General 部分的转发端口设置, OpenClash 使用原始配置文件启动失败
2023-02-03 17:13:03 错误：无法获取 DNS 部分的运行模式设置, OpenClash 使用原始配置文件启动失败
2023-02-03 17:13:01 错误：无法获取 DNS 部分的监听端口设置, OpenClash 使用原始配置文件启动失败
2023-02-03 17:13:01 错误：OpenClash 启动失败，尝试使用原始配置文件启动...
github.com/Dreamacro/clash/hub/executor/executor.go:244 +0x90
created by github.com/Dreamacro/clash/hub/executor.loadRuleProvider
	github.com/Dreamacro/clash/hub/executor/executor.go:246 +0x88
github.com/Dreamacro/clash/hub/executor.loadRuleProvider.func1()
	github.com/Dreamacro/clash/hub/executor/executor.go:222 +0xe7
github.com/Dreamacro/clash/hub/executor.loadProvider({0x7f5bd0e283e0, 0xc00012e6e0})
	github.com/Dreamacro/clash/rules/provider/provider.go:64 +0x4e
github.com/Dreamacro/clash/rules/provider.(*ruleSetProvider).Initial(0xc0000009c0)
	github.com/Dreamacro/clash/rules/provider/provider.go:118 +0x4a
github.com/Dreamacro/clash/rules/provider.NewRuleSetProvider.func1({0xf43740?, 0xc00025a588?})
	github.com/Dreamacro/clash/rules/provider/ipcidr_strategy.go:35 +0x1a5
github.com/Dreamacro/clash/rules/provider.(*ipcidrStrategy).OnUpdate(0xc0000119f8, {0xc000818000, 0x27f7, 0x22?})
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:46 +0x4b
github.com/Dreamacro/clash/component/trie.(*IpCidrTrie).AddIpCidrForString(0x3b1e8?, {0xc0006c1d70?, 0x13520a0?})
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:34 +0xb4
github.com/Dreamacro/clash/component/trie.(*IpCidrTrie).AddIpCidr(0xc0006c1d70?, 0x17?)
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:123 +0x2e
github.com/Dreamacro/clash/component/trie.addIpCidr(0x4?, 0x10?, {0xc00147c1ac?, 0x10?, 0x10?}, 0x13?)
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:146 +0x505
github.com/Dreamacro/clash/component/trie.addIpv4Cidr(0x4?, {0xc00147c1ac, 0x4, 0x100000000000013?}, 0x10)
goroutine 98 [running]:
panic: runtime error: index out of range [4] with length 4
2023-02-03 17:12:55 提示：检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...
2023-02-03 17:12:55 错误：OpenClash 启动失败，尝试还原第三方规则并重新启动 Clash 主程序...
2023-02-03 17:12:55 第六步: 等待主程序下载外部文件...
```

### Description

不好意思大佬，实在不清楚这个问题产生的原因，只能根据日志跑来这里提了，大概春节之前，我一直在openclash上使用proxy-providers配置来使用我的订阅链接，春节回来后就出现了这个报错，如果配置文件使用proxy-providers就无法启动

**Comment by Dreamacro** [comment]
你用的不是这个仓库的 clash
