### ISSUE TITLE
[Bug] clash-premium的proxy-providers名称不支持中文

### ISSUE THREAD

**Issue by wangzexi** [Dreamacro/clash#2688]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash premium 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

dreamacro/clash-premium:latest

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 1080
allow-lan: true
mode: rule
log-level: info
ipv6: true

proxy-groups:
  - name: 🚀 国外分流
    type: select
    use:
      - 香港
    proxies:
      - DIRECT

rules:
  - GEOIP,CN,DIRECT
  - MATCH,🚀 国外分流

proxy-providers:
  香港:
    type: http
    path: proxy/香港.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 3600
      url: http://www.gstatic.com/generate_204
```

### Clash log

```shell
[+] Running 1/0
 ⠿ Container clash  Created                                                                    0.0s
Attaching to clash
clash  | 21:23:14 INF [Config] start initial provider name=香港
clash  | 21:23:14 INF [Config] initial compatible provider name=🚀 国外分流
clash  | 21:23:14 INF [Inbound] Mixed(http+socks) listening addr=[::]:1080
clash  | panic: interface conversion: interface {} is *protobytes.BytesWriter, not *bytes.Buffer
clash  | 
clash  | goroutine 15 [running]:
clash  | github.com/Dreamacro/clash/common/pool.GetBuffer(...)
clash  |        github.com/Dreamacro/clash/common/pool/buffer.go:16
clash  | github.com/Dreamacro/clash/transport/ssr/obfs.(*httpConn).Write(0xc0002d27c0, {0xc0002da4a0, 0x10, 0x10})
clash  |        github.com/Dreamacro/clash/transport/ssr/obfs/http_simple.go:104 +0x6a7
clash  | github.com/Dreamacro/clash/transport/shadowsocks/shadowstream.(*Conn).initWriter(0xc0000af140)
clash  |        github.com/Dreamacro/clash/transport/shadowsocks/shadowstream/stream.go:141 +0x66
clash  | github.com/Dreamacro/clash/transport/shadowsocks/shadowstream.(*Conn).Write(0xc0000af140, {0xc0000c2888, 0x13, 0x18})
clash  |        github.com/Dreamacro/clash/transport/shadowsocks/shadowstream/stream.go:151 +0x3b
clash  | github.com/Dreamacro/clash/adapter/outbound.(*ShadowSocksR).StreamConn(0xc0000b1e80, {0xfda7a8?, 0xc0000ac678?}, 0xc000322360?)
clash  |        github.com/Dreamacro/clash/adapter/outbound/shadowsocksr.go:57 +0x14c
clash  | github.com/Dreamacro/clash/adapter/outbound.(*ShadowSocksR).DialContext(0xc0000b1e80, {0xfd2ce8, 0xc0000366f0}, 0x0?, {0x0?, 0xc000203ab8?, 0x4cc897?})
clash  |        github.com/Dreamacro/clash/adapter/outbound/shadowsocksr.go:73 +0x433
clash  | github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc0000bb2e0, {0xfd2ce8?, 0xc0000366f0?}, 0x0?, {0x0?, 0x0?, 0x0?})
clash  |        github.com/Dreamacro/clash/adapter/adapter.go:39 +0x38
clash  | github.com/Dreamacro/clash/adapter.(*Proxy).URLTest(0xc0000bb2e0, {0xfd2ce8?, 0xc0000366f0}, {0xc0000be2a0, 0x23})
clash  |        github.com/Dreamacro/clash/adapter/adapter.go:115 +0x2a5
clash  | github.com/Dreamacro/clash/adapter/provider.(*HealthCheck).check.func1()
clash  |        github.com/Dreamacro/clash/adapter/provider/healthcheck.go:68 +0x9c
clash  | github.com/Dreamacro/clash/common/batch.(*Batch[...]).Go.func1()
clash  |        github.com/Dreamacro/clash/common/batch/batch.go:52 +0x12e
clash  | created by github.com/Dreamacro/clash/common/batch.(*Batch[...]).Go
clash  |        github.com/Dreamacro/clash/common/batch/batch.go:43 +0xdb
clash exited with code 2
```

### Description

> 使用最新Docker镜像。

将`proxy-providers`名称从`香港`改为`hk`后`dreamacro/clash-premium:latest`即正常。

经测试，此问题在`dreamacro/clash:latest`中不存在。

**Comment by Dreamacro** [comment]
和是不是中文没关系，是另一个问题，已修复，等 latest 构建
