### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by comwrg** [Dreamacro/clash#300]
```

panic: runtime error: index out of range [0] with length 0

goroutine 849 [running]:
github.com/Dreamacro/clash/component/domain-trie.isValidDomain(...)
	/Users/go/src/github.com/Dreamacro/clash/component/domain-trie/tire.go:25
github.com/Dreamacro/clash/component/domain-trie.(*Trie).Search(0xc0000100f0, 0x0, 0x0, 0x1524fc0)
	/Users/go/src/github.com/Dreamacro/clash/component/domain-trie/tire.go:59 +0x238
github.com/Dreamacro/clash/tunnel.(*Tunnel).match(0xc0000d6320, 0xc00062b680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/go/src/github.com/Dreamacro/clash/tunnel/tunnel.go:217 +0xd0
github.com/Dreamacro/clash/tunnel.(*Tunnel).handleConn(0xc0000d6320, 0x15aaea0, 0xc000828a20)
	/Users/go/src/github.com/Dreamacro/clash/tunnel/tunnel.go:147 +0x21b
created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
	/Users/go/src/github.com/Dreamacro/clash/tunnel/tunnel.go:93 +0x93

```

Version: https://github.com/Dreamacro/clash/commit/09917a2a9519d1acd42b2e1b4031d169eb50203e

**Comment by comwrg** [comment]
Rollback to https://github.com/Dreamacro/clash/commit/16e3090ee85140b8f9370680cde407204cda86b6 is fine.

**Comment by Dreamacro** [comment]
fixed
