### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by codehz** [Dreamacro/clash#451]
先是一开始出现大量accept的错误
```
12月 27 21:48:57 codehz-desktop clash[477]: 2019/12/27 21:48:57 http: Accept error: accept tcp 127.0.0.1:6170: accept4: too many open files; retrying in 1s
```
跟踪后发现大量文件句柄都在clash进程内（/proc/477/fd/有上万个）
然后重启后出现如下崩溃
```
12月 27 21:48:58 codehz-desktop clash[51971]: time="2019-12-27T21:48:58+08:00" level=info msg="RESTful API listening at: 127.0.0.1:6170"
12月 27 21:48:58 codehz-desktop clash[51971]: time="2019-12-27T21:48:58+08:00" level=info msg="HTTP proxy listening at: :8888"
12月 27 21:48:58 codehz-desktop clash[51971]: panic: runtime error: invalid memory address or nil pointer dereference
12月 27 21:48:58 codehz-desktop clash[51971]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7dddad]
12月 27 21:48:58 codehz-desktop clash[51971]: goroutine 42 [running]:
12月 27 21:48:58 codehz-desktop clash[51971]: github.com/Dreamacro/clash/tunnel.(*Tunnel).handleTCPConn(0xc0000b4540, 0x9b4f40, 0xc0001340e0)
12月 27 21:48:58 codehz-desktop clash[51971]:         /build/clash/src/clash-0.16.0/tunnel/tunnel.go:229 +0x17d
12月 27 21:48:58 codehz-desktop clash[51971]: created by github.com/Dreamacro/clash/tunnel.(*Tunnel).process
12月 27 21:48:58 codehz-desktop clash[51971]:         /build/clash/src/clash-0.16.0/tunnel/tunnel.go:111 +0xac
```
版本就是0.16.0
架构：x86_64
Linux内核版本：5.5.0-rc3

**Comment by Dreamacro** [comment]
有条件试试 dev 分支

**Comment by codehz** [comment]
@Dreamacro 现在的情况是这个问题很难复现。。。就现在这个版本我也就遇到过一次这个问题。。。

**Comment by BirkhoffLee** [comment]
Closeing due to inactivity
