### ISSUE TITLE
Openwrt-x86上运行报错

### ISSUE THREAD

**Issue by KangKai1982** [Dreamacro/clash#58]
配置文件dns的fallback字段配置为8.8.4.4，运行出错，提示
```
panic: runtime error: index out of range

goroutine 75 [running]:
github.com/Dreamacro/clash/dns.(*Resolver).resolveIP(0xc00005cc80, 0xc00018d320, 0xc00015cdd8, 0xc00005cc80, 0xc00015cda0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/dns/client.go:135 +0x2b7
github.com/Dreamacro/clash/dns.(*Resolver).Exchange(0xc00005cc80, 0xc00018d320, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Dreamacro/clash/dns/client.go:77 +0x1eb
github.com/Dreamacro/clash/dns.(*Server).ServeDNS(0xc0001543a0, 0x8f8920, 0xc000189b00, 0xc00018d320)
	/home/travis/gopath/src/github.com/Dreamacro/clash/dns/server.go:20 +0x3d
github.com/miekg/dns.(*Server).serveDNS(0xc00001e600, 0xc000189b00)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.0/server.go:688 +0x2c1
github.com/miekg/dns.(*Server).serve(0xc00001e600, 0xc000189b00)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.0/server.go:573 +0x2d8
github.com/miekg/dns.(*Server).worker(0xc00001e600, 0xc000189b00)
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.0/server.go:244 +0x4d
created by github.com/miekg/dns.(*Server).spawnWorker
	/home/travis/gopath/pkg/mod/github.com/miekg/dns@v1.1.0/server.go:284 +0x86

```
注释掉fallback字段后正常

**Comment by Dreamacro** [comment]
造成的原因是从 nameserver 中并发获取的最快返回中找不到 ip 导致的，已经修复，如果找不到 ip 则取 fallback 的返回
