### ISSUE TITLE
[Bug] 异常退出 panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by a1ex4ord** [Dreamacro/clash#879]
------------------------------------------------------------------

### Clash config
<details>
  <summary>config.yaml</summary>

```yaml
    name: 'node-name'
    type: ssr
    server: server.domain.com
    port: 1234
    cipher: rc4-md5
    password: nodepassword
    protocol: auth_aes128_md5
    protocol-param: '996:userpassword'
    obfs: tls1.2_ticket_auth
    obfs-param: maybe.wechat.or.another.com
```

</details>

### Clash log
```
panic: runtime error: slice bounds out of range [61279:795]

goroutine 25566 [running]:
github.com/Dreamacro/clash/component/ssr/protocol.(*authAES128).Decode(0xc0005cbda0, 0xc0009b1800, 0x2a86, 0x3589, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/Dreamacro/clash/component/ssr/protocol/auth_aes128_md5.go:101 +0x567
github.com/Dreamacro/clash/component/ssr/protocol.(*Conn).Read(0xc0000de700, 0xc000470000, 0x5000, 0x8000, 0x0, 0x0, 0x0)
	github.com/Dreamacro/clash/component/ssr/protocol/stream.go:41 +0x290
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Read(0xc00032cfe0, 0xc000470000, 0x5000, 0x8000, 0x0, 0x0, 0x0)
	github.com/Dreamacro/clash/tunnel/tracker.go:38 +0x5f
io.copyBuffer(0x27214ff8, 0xc00032cd80, 0x27215018, 0xc00032cfe0, 0xc000470000, 0x5000, 0x8000, 0xb6fec0, 0xaa8f00, 0x27215018)
	io/io.go:405 +0x129
io.CopyBuffer(0x27214ff8, 0xc00032cd80, 0x27215018, 0xc00032cfe0, 0xc000470000, 0x5000, 0x8000, 0xc0006060a8, 0x0, 0x43f87d)
	io/io.go:378 +0x89
github.com/Dreamacro/clash/tunnel.relay.func1(0x27bd8178, 0xc00032cd80, 0x27bd8120, 0xc00032cfe0, 0xc00006bf80)
	github.com/Dreamacro/clash/tunnel/connection.go:140 +0x127
created by github.com/Dreamacro/clash/tunnel.relay
	github.com/Dreamacro/clash/tunnel/connection.go:138 +0xaa
```

### 环境 Environment

* 操作系统
Windows 10 企业版 Insider Preview
Build 20185.rs_prerelease.200731-1415
* 网路环境或拓扑
The most simple and common
pc -> router -> nerwork
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
没有
* Clash core版本
{"premium":true,"version":"2020.07.22.ge8431c7"}

### 说明 Description

slice越界，panic发生后clash core异常退出，重启clash即可恢复

### 重现问题的具体布骤 Steps to Reproduce

随机事件，从clash for windows支持ssr以来就发生这么一次
尝试复现，但是没有复现成功
log是从cfw的log目录中找到的

**我预期会发生……？**

预期不会发生slice越界，或者即使panic了也得有recover捕获住，不要让clash直接异常退出

### 可能的解决方案 Possible Solution

recover住或者提前检查防止越界

**Comment by Dreamacro** [comment]
@goomadao cc

**Comment by Dreamacro** [comment]
maybe fixed

**Comment by yuanl** [comment]
`Premium 2020.08.16` 这个Bug好像还在
* 操作系统 (the OS that the Clash core is running on)
FreeBSD OPNsense.localdomain 11.2-RELEASE-p20-HBSD

```
panic: runtime error: slice bounds out of range [:204928] with capacity 204800

goroutine 41125 [running]:
github.com/Dreamacro/clash/rules.getExecPathFromAddress(0xc0003f3b80, 0xad3820, 0xc000ab5bb0, 0x0, 0x0)
	github.com/Dreamacro/clash/rules/process_freebsd_amd64.go:148 +0x5a5
github.com/Dreamacro/clash/rules.(*Process).Match(0xc000319160, 0xc0003f3b80, 0x0)
	github.com/Dreamacro/clash/rules/process_freebsd_amd64.go:35 +0x246
github.com/Dreamacro/clash/adapters/provider.(*ruleClassicalProvider).Match(0xc00019da10, 0xc0003f3b80, 0xc00030b400)
	github.com/Dreamacro/clash/adapters/provider/rule.go:309 +0x70
github.com/Dreamacro/clash/adapters/provider.(*RuleAdaptor).Match(0xc000319a20, 0xc0003f3b80, 0xc000094d00)
	github.com/Dreamacro/clash/adapters/provider/rule.go:395 +0x3d
github.com/Dreamacro/clash/tunnel.match(0xc0003f3b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/Dreamacro/clash/tunnel/tunnel.go:383 +0x19c
github.com/Dreamacro/clash/tunnel.resolveMetadata(0xc0003f3b80, 0x0, 0x0, 0xc0005a36f0, 0xc00004de28, 0x532adc, 0xc00004de90)
	github.com/Dreamacro/clash/tunnel/tunnel.go:192 +0xc6
github.com/Dreamacro/clash/tunnel.handleTCPConn(0xcc6dc0, 0xc00030b420)
	github.com/Dreamacro/clash/tunnel/tunnel.go:318 +0x150
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:141 +0xdf

```

**Comment by Dreamacro** [comment]
@yuanl 这是 FreeBSD 的 process 规则的 panic @icpz cc

**Comment by icpz** [comment]
> `Premium 2020.08.16` 这个Bug好像还在
> 
> * 操作系统 (the OS that the Clash core is running on)
>   FreeBSD OPNsense.localdomain 11.2-RELEASE-p20-HBSD
> 
> ```
> panic: runtime error: slice bounds out of range [:204928] with capacity 204800
> 
> goroutine 41125 [running]:
> github.com/Dreamacro/clash/rules.getExecPathFromAddress(0xc0003f3b80, 0xad3820, 0xc000ab5bb0, 0x0, 0x0)
> 	github.com/Dreamacro/clash/rules/process_freebsd_amd64.go:148 +0x5a5
> github.com/Dreamacro/clash/rules.(*Process).Match(0xc000319160, 0xc0003f3b80, 0x0)
> 	github.com/Dreamacro/clash/rules/process_freebsd_amd64.go:35 +0x246
> github.com/Dreamacro/clash/adapters/provider.(*ruleClassicalProvider).Match(0xc00019da10, 0xc0003f3b80, 0xc00030b400)
> 	github.com/Dreamacro/clash/adapters/provider/rule.go:309 +0x70
> github.com/Dreamacro/clash/adapters/provider.(*RuleAdaptor).Match(0xc000319a20, 0xc0003f3b80, 0xc000094d00)
> 	github.com/Dreamacro/clash/adapters/provider/rule.go:395 +0x3d
> github.com/Dreamacro/clash/tunnel.match(0xc0003f3b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:383 +0x19c
> github.com/Dreamacro/clash/tunnel.resolveMetadata(0xc0003f3b80, 0x0, 0x0, 0xc0005a36f0, 0xc00004de28, 0x532adc, 0xc00004de90)
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:192 +0xc6
> github.com/Dreamacro/clash/tunnel.handleTCPConn(0xcc6dc0, 0xc00030b420)
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:318 +0x150
> created by github.com/Dreamacro/clash/tunnel.process
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:141 +0xdf
> ```

您好，可以稳定复现吗

**Comment by yuanl** [comment]
我不太清楚是什么情况触发的这个异常。尚未发现规律。但似乎规则添加的多，频率就高些。

**Comment by icpz** [comment]
> 我不太清楚是什么情况触发的这个异常。尚未发现规律。但似乎规则添加的多，频率就高些。

请尝试一下最新的premium，可以从d大的docker镜像里拉

**Comment by yuanl** [comment]
我的环境是BSD。Docker里面有相应的二进制文件吗？等下我用电脑看看

**Comment by Dreamacro** [comment]
@yuanl [clash-freebsd-amd64.zip](https://github.com/Dreamacro/clash/files/5175801/clash-freebsd-amd64.zip)

**Comment by yuanl** [comment]
谢谢@Dreamacro `Clash 2020.08.16-11-gaf1a58d` 已经部署了。我继续观察崩溃情况。

另外，我在日志里看见每次DNS都会提示一个错误
debug.log：
```
time="2020-09-05T07:36:58+08:00" level=debug msg="[DNS] contacts.google.com --> 172.217.x.x
time="2020-09-05T07:36:58+08:00" level=debug msg="[Process] getExecPathFromAddress error: process not found"
time="2020-09-05T07:39:02+08:00" level=debug msg="[DNS] api.github.com --> 54.169.x.x"
time="2020-09-05T07:39:02+08:00" level=debug msg="[Process] getExecPathFromAddress error: process not found"
```

部分配置文件的内容：
```yaml
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
    - '*.local'
```

**Comment by icpz** [comment]
@yuanl 有点麻烦……freebsd 12的pcb的布局和11不一样，需要一些调整。现在这个binary虽然不会panic，但是process功能在11上是坏的。麻烦等我下一个patch吧，抱歉

**Comment by yuanl** [comment]
辛苦了。
我系统更新到了`FreeBSD 12.1-RELEASE-p8-HBSD`目前没遇到崩溃的情况，不过`getExecPathFromAddress error`的错误在新旧系统还是一样的。

**Comment by icpz** [comment]
> 辛苦了。
> 我系统更新到了`FreeBSD 12.1-RELEASE-p8-HBSD`目前没遇到崩溃的情况，不过`getExecPathFromAddress error`的错误在新旧系统还是一样的。

可否提供以下命令的输出信息：

```bash
freebsd-version -ku

sysctl kern.osrelease

sysctl kern.version
```

**Comment by yuanl** [comment]
安装的是基于[HardenedBSD 12-STALBE](https://hardenedbsd.org)的[OPNsense 20.7](https://opnsense.org)
以下是输出
> freebsd-version -ku
```
12.1-RELEASE-p8-HBSD
12.1--HBSD
```
> sysctl kern.osrelease
```
kern.osrelease: 12.1-RELEASE-p8-HBSD
```
> sysctl kern.version
```
kern.version: FreeBSD 12.1-RELEASE-p8-HBSD #0  b3665671c4d(stable/20.7)-dirty: Thu Aug 27 05:58:53 CEST 2020
    root@sensey64:/usr/obj/usr/src/amd64.amd64/sys/SMP
```

**Comment by icpz** [comment]
@yuanl 
我在 `OPNsense 20.7` 上无法复现这个问题，process name可以正常工作的- -

**Comment by yuanl** [comment]
我试了一下，从本机发起的代理请求比如
```
$ curl -x http://localhost:7890 https://www.google.com/humans.txt
```
就没有任何问题。
问题出在局域网其他机器发起的代理请求。

**Comment by icpz** [comment]
> 我试了一下，从本机发起的代理请求比如
> 
> ```
> $ curl -x http://localhost:7890 https://www.google.com/humans.txt
> ```
> 
> 就没有任何问题。
> 问题出在局域网其他机器发起的代理请求。

这是by design的，因为各种代理协议都不会传递额外的进程信息给代理服务器，因此会有这条debug日志

**Comment by yuanl** [comment]
@icpz 说的无法复现指的是panic吧。’FreeBSD 12.1’的环境下已经没有panic出现了。

**Comment by icpz** [comment]
> @icpz 说的无法复现指的是panic吧。’FreeBSD 12.1’的环境下已经没有panic出现了。

我上面说的无法复现是指 `getExecPathFromAddress error` 这个无法复现，因为是本地进程请求本地代理。远程主机请求代理的时候出现这个log是正常的

**Comment by brainbush** [comment]
你好，在 Windows10 19041.630 里也出现了类似的崩溃问题，版本为 Clash v1.3.0 windows amd64 Fri Nov 20 12:55:44 UTC 2020

```
panic: runtime error: slice bounds out of range [4133:69]

goroutine 7418 [running]:
internal/poll.(*FD).Write(0xc0000d8c80, 0xc0007a4600, 0x45, 0x1025, 0x0, 0x0, 0x0)
        internal/poll/fd_windows.go:645 +0x490
net.(*netFD).Write(0xc0000d8c80, 0xc0007a4600, 0x45, 0x1025, 0xcd2f80, 0x1025, 0x0)
        net/fd_posix.go:73 +0x56
net.(*conn).Write(0xc000006060, 0xc0007a4600, 0x45, 0x1025, 0x0, 0x0, 0x0)
        net/net.go:194 +0x95
crypto/tls.(*Conn).write(0xc000a62000, 0xc0007a4600, 0x45, 0x1025, 0xc0007a2008, 0x28, 0x1006)
        crypto/tls/conn.go:914 +0x16a
crypto/tls.(*Conn).writeRecordLocked(0xc000a62000, 0x17, 0xc0007a2008, 0x28, 0x1006, 0xc602a8, 0xc0009b1800, 0x7de0b0)
        crypto/tls/conn.go:963 +0x2c5
crypto/tls.(*Conn).Write(0xc000a62000, 0xc0007a2008, 0x28, 0x1006, 0x0, 0x0, 0x0)
        crypto/tls/conn.go:1130 +0x1a6
github.com/gorilla/websocket.(*Conn).write(0xc0005b66e0, 0x0, 0x0, 0x0, 0x0, 0xc0007a2008, 0x28, 0x1006, 0x0, 0x0, ...)
        github.com/gorilla/websocket@v1.4.2/conn.go:391 +0x169
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0005847e0, 0x1, 0x0, 0x0, 0x0, 0x22, 0x22)
        github.com/gorilla/websocket@v1.4.2/conn.go:614 +0x249
github.com/gorilla/websocket.(*messageWriter).Close(0xc0005847e0, 0xc00052f000, 0x1022)
        github.com/gorilla/websocket@v1.4.2/conn.go:724 +0x69
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0005b66e0, 0x2, 0xc00052e000, 0x1022, 0x8000, 0x7ae4752aa8ac78a2, 0x413e8d823ff6d8a5)
        github.com/gorilla/websocket@v1.4.2/conn.go:773 +0x110
github.com/Dreamacro/clash/component/vmess.(*websocketConn).Write(0xc0004840c0, 0xc00052e000, 0x1022, 0x8000, 0x0, 0x0, 0x0)
        github.com/Dreamacro/clash/component/vmess/websocket.go:61 +0xb8
github.com/Dreamacro/clash/component/vmess.(*aeadWriter).Write(0xc000a6d680, 0xc0007b6000, 0x5000, 0x8000, 0x3ff0, 0x0, 0x0)
        github.com/Dreamacro/clash/component/vmess/aead.go:46 +0x3ef
github.com/Dreamacro/clash/component/vmess.(*Conn).Write(0xc0001664d0, 0xc0007b6000, 0x5000, 0x8000, 0x5000, 0x0, 0x0)
        github.com/Dreamacro/clash/component/vmess/conn.go:42 +0x59
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Write(0xc0007fc7c0, 0xc0007b6000, 0x5000, 0x8000, 0x5000, 0x0, 0x0)
        github.com/Dreamacro/clash/tunnel/tracker.go:48 +0x5c
io.copyBuffer(0x12b764be8a8, 0xc0007fc7c0, 0x12b764be8c8, 0xc0007fc3e0, 0xc0007b6000, 0x5000, 0x8000, 0xbeff20, 0xb83500, 0x12b764be8c8)
        io/io.go:411 +0x206
io.CopyBuffer(0x12b764be8a8, 0xc0007fc7c0, 0x12b764be8c8, 0xc0007fc3e0, 0xc0007b6000, 0x5000, 0x8000, 0x5, 0x5, 0xc0003ca5b0)
        io/io.go:382 +0x89
github.com/Dreamacro/clash/tunnel.relay(0x12b764be850, 0xc0007fc3e0, 0x12b764be7f8, 0xc0007fc7c0)
        github.com/Dreamacro/clash/tunnel/connection.go:147 +0x195
github.com/Dreamacro/clash/tunnel.handleSocket(...)
        github.com/Dreamacro/clash/tunnel/connection.go:131
github.com/Dreamacro/clash/tunnel.handleTCPConn(0xcd82c0, 0xc0007fc3e0)
        github.com/Dreamacro/clash/tunnel/tunnel.go:287 +0x647
created by github.com/Dreamacro/clash/tunnel.process
        github.com/Dreamacro/clash/tunnel/tunnel.go:110 +0xc5
```
